apiVersion: v1
kind: Service
metadata:
  name: frontmarket-service
spec:
  type: NodePort
  selector:
    app: frontmarket-app
  ports:
    - port: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontmarket-deployment
spec:
  selector:
    matchLabels:
      app: frontmarket-app
  template:
    metadata:
      labels:
        app: frontmarket-app
    spec:
      containers:
        - name: frontmarket
          image: ghcr.io/samimiau/front_market:main
          imagePullPolicy: Always
          ports:
            - containerPort: 3000